name: validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  global-qa-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.0
      - name: Get composer cache directory
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-8.0-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.0
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --dev
      - name: GrumPHP
        run: ./vendor/bin/grumphp run --testsuite=github_actions
      - name: PHPUnit Coverage
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./coverage.xml
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: Infection
        run: ./vendor/bin/infection
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}

  psalm-over-php-versions:
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.0', '8.1' ]
        include:
          - php-versions: 8.0
            env: COMPOSER_FLAGS="--prefer-lowest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Get composer cache directory
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}
      - name: Install dependencies
        run: composer install $COMPOSER_FLAGS --no-interaction --prefer-dist --dev
      - name: Psalm
        run: ./vendor/bin/psalm
